### ISSUE TITLE
hardware visualization

### ISSUE THREAD

**Issue by Maramaliahmed** [marvel-nccr/quantum-mobile#106]
I have a problem with my virtualbox
I am using quantum Mobile for a course, and recently I got errors starting the sessions
I attached two screenshots of the errors I had, 
I was trying to fix the problem but never succeed
I loaded new ubuntu to the virtual box  with 32bit, but it also was not opened also I reinstalled the virtualbox
please help

![er1](https://user-images.githubusercontent.com/59166114/71353391-e0da5480-25b3-11ea-9cb3-9b909fa192bd.png)

![er2](https://user-images.githubusercontent.com/59166114/71353406-ec2d8000-25b3-11ea-9c0e-3dd68327c22a.png)

**Comment by ltalirz** [comment]
Hi @Maramaliahmed  , thanks for reporting your issue.

Is there a reason why you closed the issue, i.e. were you able to resolve it?

The first error message says that hardware virtualization is not supported by your hardware - sometimes you can enable these in your BIOS settings .
I guess the second issue appears when you disable hardware acceleration in virtualbox - I did not know that this was required for running 64bit guests

**Comment by Maramaliahmed** [comment]
Hi I am new here,

**Comment by Maramaliahmed** [comment]
I enabled the hardware virtualzation from the Bios setting and the problem solved
Thank you
