### ISSUE TITLE
upcoming Quantum Mobile 20.3 release

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#107]
just wanted to use this opportunity to alert plugin developers that we're planning a new Quantum Mobile release for the first week of March (which will be used in a Wannier90 tutorial).

New plugin versions released by March 1st will be incorporated.

@yakutovicha @giovannipizzi @sphuber @bosonie @mikibonacci @broeder-j @tseplayev @albgar @normarivano

List of issues to fix with respect to RC1:
 - [x] install aiida-wannier90==2.0.0
 - [ ] ~~consider changing default python version to python3~~ Decided against - removing the bad setting from `.profile` was enough
 - [x] make sure `~/.profile` does not contain `VIRTUALENVWRAPPER_PYTHON=/usr/bin/python`
 - [x] install `graphicsmagick`
 - [x] try to understand why size grew from 3.5GB to 4.2GB
 - [x] add projwfc, pw2wannier90 utilities as codes in aiida
 - [x] update aiida-qe to alpha6
 - [x] update aiida-core to 1.1.1
 - [x] make /usr/local/share/siesta readable by non-root user (also check other /share subfolders)
 - [x] path in wannier90 AiiDA code incorrect

**Comment by ltalirz** [comment]
just a brief reminder about the upcoming release, in particular concerning the yambo and wannier90 plugins.

**Comment by mikibonacci** [comment]
Great! about yambo plugin: I just created a branch 'v1.0.0', the new stable release.

**Comment by ltalirz** [comment]
Hi @mikibonacci , thanks a lot!

I notice there is not release on PyPI yet - would you consider making it a habit to always release new tags on PyPI as well?

By the way, this can be automated e.g. on Github actions, see [docs](https://github.com/pypa/gh-action-pypi-publish) and [example](https://github.com/Materials-Consortia/optimade-python-tools/blob/master/.github/workflows/publish-on-pypi.yml)

**Comment by mikibonacci** [comment]
Yes, I will do it! thanks @ltalirz

**Comment by ltalirz** [comment]
Dear all,

I've just added a new tag 20.03.0RC1 to this repository and built an image from it that you can download here:

https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/quantum_mobile_20.03.0.ova

@giovannipizzi , @AntimoMarrazzo and @qiaojunfeng will test it on Monday - a proper release is expected for mid-week.

**Comment by giovannipizzi** [comment]
Thanks!
I will create a comment here with small issues to fix before the official release.
I start making a list and I will update it while finding new problems (if any).
I will report back when I complete my tests.

Problems found:
- `aiida-wannier90==1.0.0` is installed; should be the recently released 2.0.0 instead (py2+py3 and AiiDA 1.0 compatible, I fixed by just installing `aiida-wannier90==2.0.0` in the `aiida` venv

**Comment by qiaojunfeng** [comment]
Thanks for the new VM!
I met with the same `No module named virtualenvwrapper` error as Giovanni reported. I am just considering maybe we can use `update-alternatives` to symlink `/usr/bin/python` to `python3`? 

I am testing the VM and will report here problems I meet with.

**Comment by ltalirz** [comment]
Thanks for all your reports - please keep posting any issues; I'll try to fix them all collectively once you're done

**Comment by albgar** [comment]
Thanks for all the work.

The psf pseudopotentials in /usr/local/share/siesta cannot be read by a non-root user. The last ('*-psf') directories in the hierarchy do not belong to root and have the wrong permissions (probably an issue with unpacking the tar file I created on my machine...)

**Comment by giovannipizzi** [comment]
Both me and @qiaojunfeng have finished checking the VM and have no further comments.
As a note/question - the ansible-role-quantum-espresso also defines a wannier90 code, is this disabled by default, and replaced by the one of the wannier90 role? The Wannier90 from QE might not be at the most up-to-date version.

**Comment by ltalirz** [comment]
> the ansible-role-quantum-espresso also defines a wannier90 code, is this disabled by default, and replaced by the one of the wannier90 role? The Wannier90 from QE might not be at the most up-to-date version.

Yes, for the moment, I removed wannier90 from the QE role.

I started preparing the release on Saturday / Sunday and intend to finish today.

**Comment by ltalirz** [comment]
Done!
