### ISSUE TITLE
decide size targets

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#11]
One feedback from Mohamad:
In another course, they were asked to download a VM
 * zipped VM: 6.6GB
 * unzipped VM: 17GB
i.e. 25GB of space altogether. This persuaded him to rather install everything by himself.

We are currently at:
 * .ova image: 3.0GB
 * virtual box size: 7.0GB
What should we be aiming for in the "base version"?

Personally, I find 10GB acceptable, but we should be careful to not go too much beyond that.
Also, I have never had to space-optimise linux systems, so perhaps someone more knowledgable could give some tips here...

**Comment by giovannipizzi** [comment]
I agree that 10 GB is ok and we should try not the have a Vbox size over that (not including the .ova).

A few things we might do:
- remove some packages (we install ubuntu-desktop that is quite complete, but I'm sure half of the things are not useful). We can see the list of packages that are installed, and install only the needed ones (better to install what we need than to uninstall afterwards. Note: some gnome and similar packages are needed to have the GUI work correctly. But for instance we can remove things like LibreOffice?)  
- we should run a `sudo apt-get clean` in a final 'cleaning-up' role (this frees up at least 500MB currently).
- `~.cache` also is currently at 220 MB; we can clean up also `/root/.cache` even if this is small
And probably there is still something that we can clean up (let's and them here and then work on it)

**Comment by giovannipizzi** [comment]
Currently, `ubuntu-desktop` has the following dependencies:
```
Depends: alsa-base, alsa-utils, anacron, at-spi2-core, bc, ca-certificates, 
checkbox-gui, dmz-cursor-theme, doc-base, fonts-dejavu-core, 
fonts-freefont-ttf, foomatic-db-compressed-ppds, genisoimage, 
ghostscript-x, gnome-menus, gnome-session-canberra, gstreamer1.0-alsa, 
gstreamer1.0-plugins-base-apps, gstreamer1.0-pulseaudio, gvfs-bin, 
inputattach, language-selector-gnome, libatk-adaptor, libnotify-bin, 
libsasl2-modules, lightdm, memtest86+, nautilus, notify-osd, openprinting-ppds, 
printer-driver-pnm2ppa, pulseaudio, rfkill, software-properties-gtk, 
ubuntu-artwork, ubuntu-drivers-common, ubuntu-release-upgrader-gtk, 
ubuntu-session, ubuntu-settings, ubuntu-sounds, unity, unity-control-center, 
unity-greeter, unity-settings-daemon, unzip, update-manager, 
update-notifier, wireless-tools, wpasupplicant, xdg-user-dirs, xdg-user-dirs-gtk, 
xdiagnose, xkb-data, xorg, yelp, zenity, zip
```
and the recommended packages (that are installed by default):
```
Recommends: a11y-profile-manager-indicator, acpi-support, 
activity-log-manager, aisleriot, app-install-data-partner, apport-gtk, 
avahi-autoipd, avahi-daemon, baobab, bluez, bluez-cups, branding-ubuntu, 
brltty, cheese, cups, cups-bsd, cups-client, cups-filters, deja-dup, eog, 
evince, example-content, file-roller, firefox, fonts-guru, fonts-kacst-one, 
fonts-khmeros-core, fonts-lao, fonts-liberation, fonts-lklug-sinhala, 
fonts-nanum, fonts-noto-cjk, fonts-sil-abyssinica, fonts-sil-padauk, 
fonts-takao-pgothic, fonts-thai-tlwg, fonts-tibetan-machine, fwupd, 
fwupdate, fwupdate-signed, gedit, gnome-accessibility-themes, 
gnome-bluetooth, gnome-calculator, gnome-calendar, gnome-disk-utility, 
gnome-font-viewer, gnome-keyring, gnome-mahjongg, gnome-mines, 
gnome-orca, gnome-power-manager, gnome-screensaver, gnome-screenshot, 
gnome-sudoku, gnome-system-log, gnome-system-monitor, gnome-terminal, 
gnupg-agent, gucharmap, gvfs-fuse, hplip, ibus, ibus-gtk, ibus-gtk3, 
ibus-table, im-config, kerneloops-daemon, laptop-detect, libgail-common, 
libnss-mdns, libpam-gnome-keyring, libproxy1-plugin-gsettings, 
libproxy1-plugin-networkmanager, libqt4-sql-sqlite, libreoffice-calc, 
libreoffice-gnome, libreoffice-impress, libreoffice-math, libreoffice-ogltrans, 
libreoffice-pdfimport, libreoffice-style-breeze, libreoffice-writer, 
libwmf0.2-7-gtk, mousetweaks, nautilus-sendto, nautilus-share, 
network-manager-gnome, network-manager-pptp-gnome, onboard, 
overlay-scrollbar-gtk2, pcmciautils, plymouth-theme-ubuntu-logo, 
policykit-desktop-privileges, ppp, pppconfig, pppoeconf, printer-driver-brlaser, 
printer-driver-c2esp, printer-driver-foo2zjs, printer-driver-min12xxw, 
printer-driver-ptouch, printer-driver-pxljr, printer-driver-sag-gdi, 
printer-driver-splix, pulseaudio-module-bluetooth, pulseaudio-module-x11, 
python3-aptdaemon.pkcompat, qt-at-spi, remmina, rhythmbox, seahorse, 
shotwell, simple-scan, snapd, sni-qt, speech-dispatcher, 
system-config-printer-gnome, thunderbird, thunderbird-gnome-support, 
totem, transmission-gtk, ttf-ancient-fonts-symbola, ttf-ubuntu-font-family, 
ubuntu-docs, ubuntu-software, unity-accessibility-profiles, 
unity-webapps-common, usb-creator-gtk, vino, whoopsie, xcursor-themes, 
xdg-utils, xterm, xul-ext-ubufox, zeitgeist-core, zeitgeist-datahub
```

**Comment by giovannipizzi** [comment]
I would probably leave all the necessary packages, and instead remove some of the recommended ones? Now that I look the list is pretty massive, maybe better to remove selectively what we know we don't want, to have the asnsible scripts more resilient to upgrade of ubuntu versions?
Probably some of the things I would remove include:
- cups, cups-bsd, cups-client, cups-filters (we don't need to support printers)
- printer-driver-*
- fonts-* (maybe we just choose a few that are used by default)
- gnome-calendar
- gnome-font-viewer
- gnome-mahjongg, gnome-mines, gnome-sudoku, ... (and other games)
- libreoffice-* (unless we want to leave libreoffice-calc for making simple plots??)
- rhythmbox (we don't need music players)
- thunderbird, thunderbird-gnome-support
- ubuntu-docs

**Comment by giovannipizzi** [comment]
after running `sudo apt-get remove cups cups-bsd cups-client cups-filters 'printer-driver-*' fonts-* gnome-calendar gnome-font-viewer gnome-mahjongg  gnome-mines gnome-sudoku libreoffice-* rhythmbox thunderbird thunderbird-gnome-support ubuntu-docs` followed by `sudo apt-get autoremove` we went down by another 600MB.
**Note**: in this case adapt the 'customisation' role to remove the two icons of libreoffice from the launcher.

Some of the other things listed probably can be removed but I don't know what they do and if they are essential.
We should also check that everything still works... On the other hand, for some plotting libraries (even matplotlib) maybe it would be good to add a "minimal" latex installation? (this risks to be big, though)

**Comment by giovannipizzi** [comment]
Maybe we can also remove `jmol` from the list of installed packages - anyway now it does not work, unless we install java...

**Comment by giovannipizzi** [comment]
Another comment - we can remove the source code of codes, or at least remove the .o and similar files at the end.

A few notes:
- This should be done only in a final "cleanup" step before making the OVA - otherwise everytime one reruns ansible, it will have to recompile the codes
- for QE, do NOT do `make clean` - I just did it, but this cleans also the .x files...
- for QE the problem is not huge, but the size will add up when adding also other codes (see also #3)
- sometimes it's better to keep the source code in case someone wants to look into it? Otherwise we just clean all - what we can do is a `cp --dereference ~/codes/pw-6.1/bin destdir` to copy only the executables (the files and not the symlinks), then `rm -r ~/codes/pw-6.1/*` and finally `mv destdir ~/codes/pw-6.1/bin` to keep only the binaries? (again, as a final cleanup process)

**Comment by ltalirz** [comment]
Thanks for the hints!

A few comments:
 * The way to do this in ansible is to notify a handler (handlers just run, when something changed). See cbe6dccfcc7f55c8a827eda504b375f0133dbb6b
 * Is `apt autoremove` safe? Doesn't it remove all packages that no other packages depend on?

**Comment by giovannipizzi** [comment]
Ok thanks!

- I think anyway it's good to have a final 'apt clean' call in a cleanup phase/role (as somewhere the notification with be forgotten)
- instead of `~/.cache` I would use the ANSIBLE HOME variable as done elsewhere
- autoremove should remove all packages that no other packages depend on AND that were not installed manually so it will do nothing if you never uninstalled anything. It's useful to remove what was installed as a dependency of something you uninstalled. So it should be safe in our case.

**Comment by giovannipizzi** [comment]
Interesting link (but very outdated! it's from 2008!) https://help.ubuntu.com/community/Diet%20Ubuntu

**Comment by ltalirz** [comment]
Regarding the removal of unnecessary packages (+autoremove):
I'm not quite sure how to marry this with the 'idempotency' concept. If one does it just naively,  then our `apt install ubuntu-desktop` will re-install those packages every time.

So, do you agree that the way forward is to, instead, come up with a list of packages that we *do* need? Perhaps by installing ubuntu desktop, then removing unnecessary packages, then autoremove and then listing all installed packages?

**Comment by giovannipizzi** [comment]
Looks ok.
I would then replace the `apt install ubuntu-desktop` with the explicit list of packages I list above, minus the ones I say we can remove.
We can always keep removing stuff later.
Thanks!

**Comment by ltalirz** [comment]
I wasted a few hours on this problem on Friday... it's not that trivial.
One can install `ubuntu-desktop` with `--no-install-recommends` but then it also seems to skip the recommended packages of the required dependencies (which causes numerous problems, e.g. lightdm fails to start).
In the `slim-ubuntu-desktop` branch, I've started adding these packages back in, but it's a bit of a pain because it's not that easy to figure out which missing packages actually cause the problems. Also, this list of packages might change in and I don't think we want to maintain it.
Of course, instead of installing `ubuntu-desktop` one could also just take the list of packages required by `ubuntu-desktop` and install those directly. However, also this list may be subject to change.

I've added a [question](https://askubuntu.com/questions/964723/is-there-a-non-recursive-no-install-recommends-for-apt-get-install) on askubuntu to see whether there is a maintainable way of achieving what we want.

**Comment by ltalirz** [comment]
Another possibility would be to switch to the [LXDE](http://lxde.org/) - on top of Ubuntu or even on top of the lighter [LUbuntu](http://lubuntu.net/).

Currently there is no LUbuntu [bento](https://github.com/chef/bento) image, so this is not an option for the moment.

Installing LXDE on top of Ubuntu works fine (just replace `apt-get install ubuntu-desktop` by `apt-get install lxde lxde-common`), and the image size after the `common` ansible tasks are
 * ubuntu + ubuntu-desktop: 2.4GB 
 * ubuntu + lxde: 1.5 GB

However, the result would need a bit of work...
![screen shot 2017-11-07 at 19 14 11](https://user-images.githubusercontent.com/1053245/32510199-fdc8ad08-c3ef-11e7-80d2-5643d716093a.png)

**Comment by ltalirz** [comment]
In summary:

To do:
 - [ ] `rm -rf ~/.cache` (421MB on 18.10RC1)
 - [ ] `rm -rf /root/.cache` (4MB on 18.10RC1) 
 - [ ] `sudo apt-get clean` (979MB on 18.10RC1)
 - [ ] `rm -rf /var/lib/apt/lists/*` (178MB on 18.10RC1)

Not to do:
 * remove source code of simulation codes (might be helpful)
 * remove packages from ubuntu-desktop manually (destroys idempotency + can introduce problems) or try to hand-pick every package to install (tedious to maintain)
 * switch to lighter LXDE (looks outdated)

**Comment by giovannipizzi** [comment]
Is it worth trying lubuntu? https://www.ubuntu.com/download/flavours I don't know if 1) it's lighter 2) there are bento boxes or similar to start with

**Comment by ltalirz** [comment]
Concerning lubuntu/lxde, see comment above.
I think staying with the default ubuntu desktop is a good choice for the moment.

**Comment by giovannipizzi** [comment]
Ok, but note that
> Lubuntu is a light, fast, and modern Ubuntu flavor using LXQt as its default desktop environment. Lubuntu used to use LXDE as its default desktop environment.

**Comment by ltalirz** [comment]
Ah sorry - I missed that. Opened #84 for this, so we can close this one once.

To-do list completed in marvel-nccr/ansible-role-ubuntu-desktop@73d92233cce43100399c1c1c104ea9141a6957f5
