### ISSUE TITLE
Issue to fix in v20.03.1

### ISSUE THREAD

**Issue by AntimoMarrazzo** [marvel-nccr/quantum-mobile#113]
List of bugs to fix in 20.03.1, obtained developing the Oxford 2020 Wannier-AiiDA tutorial.

**Comment by AntimoMarrazzo** [comment]
SSSP v1.1 is not loaded in AiiDA by default, so verdi data upf listfamilies returns
_Warning: No valid UPF pseudopotential family found._

**Comment by AntimoMarrazzo** [comment]
In the VM the aiida-quantumespresso is stil 3.0.0a5, while it should be 3.0.0a6 in order to include the "testing" protocol.

**Comment by ltalirz** [comment]
I've fixed the changes; let me know when this additional package is ready and how to install it 

@giovannipizzi for info

**Comment by giovannipizzi** [comment]
Thanks @ltalirz!
There are two more things:
- install the [aiida-wannier90-workflows](https://pypi.org/project/aiida-wannier90-workflows/) package (version 1.0.0), just released - this could be make part of the aiida-wannier90 role
- install aiida-wannier90 2.0.1, that we are going to release [in the next few hours](https://github.com/aiidateam/aiida-wannier90/pull/96) - we will ping back when it's released

After this and the fixes discussed above, ok for us to make a new release! Let us know if you want us to test it before "official" release

**Comment by giovannipizzi** [comment]
Released [aiida-wannier90==2.0.1](https://pypi.org/project/aiida-wannier90/2.0.1/), so this can now be included, and the QM can be generated (note that this might require to update the release notes).
Thanks!

**Comment by ltalirz** [comment]
I'm basically ready to create the new image but this takes some time.
Would you consider fixing this first: https://github.com/aiidateam/aiida-wannier90-workflows/issues/1

**Comment by ltalirz** [comment]
and this: https://github.com/aiidateam/aiida-wannier90-workflows/issues/2

**Comment by giovannipizzi** [comment]
aiida-wannier-workflows 1.0.1 released

**Comment by ltalirz** [comment]
Here is the updated image:

https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/quantum_mobile_20.03.1.ova

Let me know whether it looks fine and I will make the release.

**Comment by qiaojunfeng** [comment]
I have run one workflow in the newest VM, everything works smoothly, thanks!
@giovannipizzi do we need more tests?

**Comment by giovannipizzi** [comment]
I asked @qiaojunfeng to do a few more tests, and all seem to work. So ok for us to release! And thanks *a lot* Leopold for the hard work!!

**Comment by ltalirz** [comment]
new version released at https://github.com/marvel-nccr/quantum-mobile/releases/tag/20.03.1 :-)
