### ISSUE TITLE
consider increasing default disk size limit

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#115]
the size limit of the virtual disk is currently set to 64 GB; one student complained that they could not increase it.

Although it's quite easy to increase, there is no strong need for such a low limit (or any particular limit). We could think about increasing it to, say 128GB or 256 GB.

**Comment by borellim** [comment]
The virtual disk size is determined by the provider of the [Vagrant box](https://app.vagrantup.com/bento/boxes/ubuntu-18.04).
Some steps to increase it might be:
- `vagrant plugin install vagrant-disksize`
- `config.disksize.size = '128GB'`
- resize the partition and the filesystem (this may be tricky for idempotency)
See [here](https://medium.com/@kanrangsan/how-to-automatically-resize-virtual-box-disk-with-vagrant-9f0f48aa46b3) and [here](https://askubuntu.com/a/1015068/593368).

**Comment by ltalirz** [comment]
ah hm, I thought increasing it in the `Vagrantfile` would be enough.
If it's complicated, I'm not sure we should invest time into this

**Comment by ltalirz** [comment]
Closing this for now, since there did not seem to be further requests for this
