### ISSUE TITLE
merge repository with cloud edition?

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#117]
This is for @borellim and @chrisjsewell to provide some context to the status quo.

This repository currently holds the ansible playbook, vagrant file (+ more utility scripts) for the Desktop Edition of Quantum Mobile.
The Cloud Edition is kept in a [separate repository](https://github.com/marvel-nccr/quantum-mobile-cloud-edition).

This split was made because the prerequisites and installation instructions for the two approaches are quite different: for the cloud edition you don't need vagrant/virtualbox, which makes things a lot simpler and allows the cloud edition repository to be cleaner (many scripts are not needed, etc.).

Of course the split increases the maintenance burden a bit, but porting updates in the `playbook.yml` and the `requirements.yml` is very straightforward, and I am not sure whether merging the two repos is the better approach.

In case you want to go down that route:
 * think about whether you want to have a `qm-desktop.yml` playbook and a `qm-cloud.yml` playbook, or whether you want to merge both into one (where some roles are skipped based on environment variables).
 * I feel the current approach of having all installation instructions in the README would then no longer work well, and one would have to move things to the wiki.

**Comment by chrisjsewell** [comment]
done!
