### ISSUE TITLE
Decide RAM targets

### ISSUE THREAD

**Issue by borellim** [marvel-nccr/quantum-mobile#120]
See issues #11 and #84.
See PR #119.

Screenshots from a machine configured with 2 GB RAM.
Right after reboot:
![Schermata del 2020-07-03 01-57-11](https://user-images.githubusercontent.com/6683587/86419052-74fb4600-bcd2-11ea-9a1b-7382752c10b5.png)
After some minutes:
![Schermata del 2020-07-03 02-11-39](https://user-images.githubusercontent.com/6683587/86419087-8a707000-bcd2-11ea-8acd-b665ee98b9d1.png)
Before a reboot, while installing codes (BigDFT):
![Schermata del 2020-07-03 01-17-09](https://user-images.githubusercontent.com/6683587/86419107-98be8c00-bcd2-11ea-967b-02170df993c9.png)
![Schermata del 2020-07-03 01-17-00](https://user-images.githubusercontent.com/6683587/86419135-a83dd500-bcd2-11ea-8849-25e4c2973262.png)

**Comment by ltalirz** [comment]
Hi Marco, thanks for the stats - as one can see from your "while installing BigDFT" graph, the system isn't swapping at 2GB RAM.
What would interest me is the same graph at 1.5GB or 1GB - if the system does indeed start swapping (perhaps you have seen it already), then I agree that an increase in RAM is warranted.

**Comment by ltalirz** [comment]
RAM was increased to 2GB by @borellim in fe619eab29f640db6460b8f43bffbf2e81674eda and then reduced to 1.5GB in 8d23c7fdd8e9a44137b805d879df73e178fd04b1 (both on Jul 3rd, 2020).
No further explanation provided in the commit message.

I'm assuming this was discussed internally and am closing this.
