### ISSUE TITLE
Use of `md5` in create_image.sh

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/quantum-mobile#122]
[This change](https://github.com/marvel-nccr/quantum-mobile/commit/7eafef2798ebf0184c8420ed95f027a92a4d7ab9#r40414318) is not correct for mac OSX, whereby `md5` is available not `md5sum`.
Perhaps we add a command to choose what command is available?

**Comment by borellim** [comment]
Hey, sorry about this. Thanks for opening the issue.

Since I don't have a mac, would you be able to test the following snippet and show me the output?
```bash
if checksum=$(md5 README.md 2>/dev/null); then
    echo "(MAC) md5: $checksum"
else
    checksum=$(md5sum README.md 2>/dev/null);
    echo "(LINUX) md5sum: $checksum"
fi
```

**Comment by chrisjsewell** [comment]
not required now that its handled by ansible 😄
