### ISSUE TITLE
Change SSSP download from legacy-archive to archive

### ISSUE THREAD

**Issue by borellim** [marvel-nccr/quantum-mobile#126]
This is the mirror for the Desktop edition of this issue: https://github.com/marvel-nccr/quantum-mobile-cloud-edition/issues/17

It applies to ansible roles: [marvel-nccr.aiida](https://github.com/marvel-nccr/ansible-role-aiida) and [marvel-nccr.quantum_espresso](https://github.com/marvel-nccr/ansible-role-quantum-espresso)

**Comment by chrisjsewell** [comment]
copy if issue details:

In any case, for Chris (if this is the most recent commit): don’t use legacy-archive, that will go away at some point.
Use the URLs you find in this page:
archive.materialscloud.org/record/22
(E.g. for SSSP efficiency: archive.materialscloud.org/record/file?file_id=8a94cb23-2c11-422f-9290-22392dbc355b&record_id=22&filename=SSSP_efficiency_pseudos.tar.gz)

As these should stay.

Also, not for this release of QM, but I suggest for the next one you open an issue to use the /v4 of the archive:
archive.materialscloud.org/record/23

(Note that the layout of the tar.gz changed - in the AiiDA tutorial I changed the commands to run correctly with the new file).

This applies to the aiida and quantum-espresso roles.
In the long term, we may actually want to remove the pseudopotential downloads from the quantum-espresso role and just import them via marvel-nccr/ansible-role-aiida#35

**Comment by chrisjsewell** [comment]
fixed in https://github.com/marvel-nccr/ansible-role-quantum-espresso/pull/9
