### ISSUE TITLE
Startup ubuntu and Linux OS on VirtualBox 

### ISSUE THREAD

**Issue by Shokr-190** [marvel-nccr/quantum-mobile#130]
Hello,
 After installing the VirtualBox6.1 and setup the ubuntu files, I encountered a message in the first startup of the ubuntu, it asked me "login" and "password"!

**Comment by ltalirz** [comment]
Hi @Shokr-190 - you can find the login credentials in the installation instructions
https://github.com/marvel-nccr/quantum-mobile/releases/tag/20.06.1

**Comment by Shokr-190** [comment]
Dear Italirz,
Thanks for your comment. 
If you mean this "Login credentials: username: max, password: moritz."
I entered the Login and password before, but got an error!

**Comment by ltalirz** [comment]
Oh, I see. What is the error you get?

It is true that, ideally, you should not even be asked for the login credentials as we have autologin enabled.
There is a long-standing glitch in the Ubuntu Desktop autologin procedure that I never managed to fully get rid of: https://github.com/marvel-nccr/quantum-mobile/issues/93

If this is the issue you encountered, you can simply restart the VM and it should log you in automatically
