### ISSUE TITLE
Update Roles to GH-Actions

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/quantum-mobile#132]
All roles should be standardised to use GH-actions, plus the same code style and test infrastructure.

Also testing, where possible, should be updated to run against ubuntu 20.04, rather than 16.04, since 16.04 ships with python 3.5, which aiida-core no longer supports.

I have done this in https://github.com/marvel-nccr/ansible-role-aiida/pull/45, and pulled out the common files (replacing the role name with a jinja variable `{{  name }}`) into:

https://gist.github.com/chrisjsewell/c8b4465e1bc006f483d9313d3a33eff4

_Originally posted by @ltalirz in https://github.com/marvel-nccr/ansible-role-aiida/pull/45#issuecomment-704768776_

P.S. It might be useful to open an issue on quantum mobile to keep track the progress of moving roles to github actions.

Since there are >30 roles it might be worth thinking about a (semi-)automated way of migrating a role (run some script, ...); I still remember when I needed to move roles to molecule 3 and I thought automation wasn't necessary but in the end I might have saved a bit of time since one easily makes mistakes when doing everything by hand.

**Comment by chrisjsewell** [comment]
Also https://github.com/marvel-nccr/cookiecutter-ansible-role should be updated

**Comment by chrisjsewell** [comment]
I think that's just about all the roles that are actively used in the quantum mobile build now updated

**Comment by ltalirz** [comment]
Thanks a lot for this @chrisjsewell !

Any further roles can be updated later
