### ISSUE TITLE
Add "working with" instructions for cloud VMs

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/quantum-mobile#135]
Basically, in the readme and/or wiki, copy and/or link to https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_ISSP_Chiba_Japan/sections/setup.html

**Comment by ltalirz** [comment]
This should be taken care of by the "Launching Quantum Mobile" section of the docs
https://quantum-mobile.readthedocs.io/en/latest/users/launch.html

Feel free to reopen if something else is missing.
