### ISSUE TITLE
Error opening evince for the first time

### ISSUE THREAD

**Issue by borellim** [marvel-nccr/quantum-mobile#138]
Marnik reports a problem opening evince for the first time on an AWS machine, connected from an older MacBook.

> The first time I try to open a pdf, for example to look at a provenance graph I just generated, I get the following errors:
> (aiida) max@quantum-mobile:~/workflow_basic$ evince 2151.dot.pdf 
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Afterwards, the command works just fine, though (And possibly also the first time, I killed the command once I saw the errors).

I could not reproduce the problem from the Ubuntu 16.04 laptop, on either Cloud or Desktop edition, using ubuntu or max user.
The source may be a local misconfiguration (a google search seems to point to driver problems).

Since the problem only appears the first time, I am ignoring it for now. This thread is to have a reference in case it happens again.

**Comment by ltalirz** [comment]
I assume no further reports of this issue have surfaced since the 2020 tutorial, so I'm closing this.
