### ISSUE TITLE
download size of qm 20.11.2a

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#156]
@chrisjsewell I see that QM size increased from 3.4GB (9.9GB extracted) at 20.6.1 to 4.4GB (13.2GB extracted) at 20.11.2a.
I.e. it takes an extra 3.3GB on disk.

Do you happen to know why?

**Comment by chrisjsewell** [comment]
Well the distribution has increased from 6 simulation codes to 8, plus siesta now has more dependencies, plus an extra python virtual environment for jupyter. 

20.6.1:
- Quantum Espresso 6.5
- Yambo 4.5.1
- fleur 0.30 MaX4
- siesta v4.1-rc1
- cp2k 7.1
- Wannier90 3.1.0

20.11.2a:
- Quantum ESPRESSO 6.5
- Yambo 4.5.2
- fleur 0.30 MaX4
- cp2k 7.1
- Wannier90 3.1.0
- siesta MaX-1.2.0
- bigdft 4855f2cd
- abinit 9.2.1

But obviously if you can identify any ways to "trim the fat" that would be great 😄

**Comment by chrisjsewell** [comment]
Note the "Disk Usage Analyzer" application is included in the VM, so can be used to look at this.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/2997570/111621719-9ceef300-87e8-11eb-90d3-9c72c59b694e.png">

A number of things of note:

- There are some clean-up tasks in `roles/marvel-nccr.simulationbase/tasks/cleanup.yml`, but this feels like a bit of an odd place for it (and easy to overlook). I would just remove this and add a separate playbook with clean tasks:
  - Clear apt cache and `apt-get clean` and `rm -rf /var/lib/apt/lists/*`
  - Clear pip cache: `pip cache purge` (but should be taken care of by removing `~/.cache`)

- Remove Python 2.7 install (210 Mb in `/usr/lib/python2.7`). It's installed in `roles/marvel-nccr.ansible_prerequisites/tasks/main.yml`, but I imagine this is no longer required by ansible. In fact I'm not sure if ansible_prerequisites is required at all now.

- The jupyter virtual env can be reduced by ~500Mb with `jupyter lab clean` ([see jupyter lab docs](https://jupyterlab.readthedocs.io/en/latest/user/directories.html#jupyterlab-build-process))

<img width="437" alt="image" src="https://user-images.githubusercontent.com/2997570/111620866-8e540c00-87e7-11eb-9873-98f33fb44dba.png">

- The biggest stuff in the aiida virtual env are bokeh and plotly, which come from the aiidalab install

<img width="449" alt="image" src="https://user-images.githubusercontent.com/2997570/111620779-754b5b00-87e7-11eb-853a-57c44feb15d8.png">

- The binaries take up 1.6 Gb, I imagine this is unavoidable
- The psuedopotentials take up >300 Mb: the downloads made in `roles/marvel-nccr.aiida/tasks/aiida-pps.yml` to the `aiida` can be removed, once they are imported to reclaim ~80Mb (moving to aiida-psuedo use should also not leave these files). Then the question is whether we really need to also have the "raw" psuedo files available - downloaded in `roles/marvel-nccr.quantum_espresso/tasks/pps.yml` and `roles/marvel-nccr.siesta/tasks/psml-pps.yml` - or if they are just stored as families in the aiida database. I imagine you could want them, if you were just using the codes without aiida, but do we need to account for that.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/2997570/111622829-eb50c180-87e9-11eb-8c06-cec750ce3d58.png">

**Comment by ltalirz** [comment]
thanks for looking into this!

> Then the question is whether we really need to also have the "raw" psuedo files available

I think we want to keep them. QM is not just for AiiDA use.

**Comment by ltalirz** [comment]
By the way, if we were to use conda to install cp2k, qe, siesta, ... some dynamically linked libraries could be reused.
E.g. the cp2k binary from conda is just 38MB instead of 304MB

**Comment by chrisjsewell** [comment]
how much space does Conda take up in general?

**Comment by chrisjsewell** [comment]
> Remove Python 2.7 install (210 Mb in /usr/lib/python2.7). It's installed in roles/marvel-nccr.ansible_prerequisites/tasks/main.yml, 

Implemented in: https://github.com/marvel-nccr/quantum-mobile/commit/d27a90d2bb317d6c551e6535a799a4430fad08ae

> The psuedopotentials take up >300 Mb: the downloads made in roles/marvel-nccr.aiida/tasks/aiida-pps.yml to the aiida folder can be removed, once they are imported to reclaim ~80Mb

Implemented in: https://github.com/marvel-nccr/ansible-role-aiida/commit/cbb17a5c330fcd433e0d05006013c8458f320cb2

> The jupyter virtual env can be reduced by ~500Mb with jupyter lab clean

Implemented in: https://github.com/marvel-nccr/ansible-role-aiidalab/commit/7403438bc290b1e105e818afc698869ea7e4bce0

With all these in place I have created https://quantum-mobile.readthedocs.io/en/latest/releases/both/21.03.18-qe.html, from https://github.com/marvel-nccr/quantum-mobile/blob/main/playbook-build-qe.yml, which only contains the quantum espresso code and aiida plugin (plus aiidalab etc)

This produces a 3.5 GB VM (10.4 GB extracted) and 1.52 GB Docker image on Docker hub (4.4 Gb extracted)

**Comment by ltalirz** [comment]
great, thanks!
I consider this issue addressed then; we can still come back to it in the future for further ideas on reducing image size (there are others as well https://github.com/marvel-nccr/quantum-mobile/issues/84 ).

**Comment by chrisjsewell** [comment]
As a reference baseline, here also is some snapshots of the VM, created with no simulation code or aiidalab roles (just the aiida role), and after running cleanup:

![image](https://user-images.githubusercontent.com/2997570/115029302-249e4f00-9ec6-11eb-8875-925b04fb46bb.png)
![image](https://user-images.githubusercontent.com/2997570/115029404-3b44a600-9ec6-11eb-9a8d-e4da995a89fc.png)
![image](https://user-images.githubusercontent.com/2997570/115029517-59aaa180-9ec6-11eb-9b2f-70a2f0acb55d.png)
![image](https://user-images.githubusercontent.com/2997570/115029711-8ced3080-9ec6-11eb-8392-3eeb1fb96ea7.png)

**Comment by ltalirz** [comment]
you may want to consider using something like [filelight](https://www.tecmint.com/filelight-analayze-disk-usage-statistics-in-linux/) that gives a multi-level breakup

libreoffice might be a candidate for removal, but of course there is also a benefit to not worrying about the ubuntu defaults.
