### ISSUE TITLE
The AiiDAlab and Jupyter Lab cannot be reached from outside the container

### ISSUE THREAD

**Issue by csadorf** [marvel-nccr/quantum-mobile#166]
# Problem

It is not possible reach either AiiDAlab or Juptyer lab from outside the container at the moment. 

# To reproduce

Start the docker-compose network as described [here](https://quantum-mobile.readthedocs.io/en/latest/users/launch.html#docker-container), start AiiDAlab as described [here](https://quantum-mobile.readthedocs.io/en/latest/users/use.html#working-with-jupyter-and-aiida-lab) and then try to reach the server from the host machine, e.g., with `curl -L http://localhost:8888`.

# Proposed fix

I was able to get this to work by adding the following line to the `/usr/local/bin/aiida-aiidalab` file:
```diff
@@ -8,5 +8,6 @@
 else
     jupyter notebook --notebook-dir="/project" \
       --NotebookApp.default_url="/apps/apps/home/start.ipynb" \
+      --ip="0.0.0.0" \
       --port=${1:-8888}
 fi
```
I assume that the same patch would fix the issue with `aiida-jupyterlab`.

**Comment by chrisjsewell** [comment]
thanks @csadorf!
I guess we should check that this still works within the VirtualBox VM, or if this should only be added for Docker platform builds

**Comment by csadorf** [comment]
@chrisjsewell Unfortunately I will not be able to help with that, because my laptop simply does not have enough disk space to execute the QM VM at the moment.

**Comment by chrisjsewell** [comment]
thats ok, just a note-to-self
