### ISSUE TITLE
Missing network interface

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#167]
When I start Quantum Mobile 20.11.2a (on VirtualBox 6.1.16 on a Mac) I get this error:
<img width="528" alt="Screenshot 2021-03-07 at 20 19 43" src="https://user-images.githubusercontent.com/16132028/110251909-24379d80-7f83-11eb-8a1f-69c42e11b486.png">

This wasn't there with earlier versions.
Apparently the problem is that also the second network adapter is enabled; if I disable it, it starts normally.
Can the second network adapter be left disabled?

**Comment by chrisjsewell** [comment]
Out of interest what version of OSX are you running?
I have VB 6.1.16 on Catalina and have not observed this issue

**Comment by chrisjsewell** [comment]
This is likely enabled as the network required for ansible to provision the VM, so I'm sure how to automate disabling it: https://github.com/marvel-nccr/quantum-mobile/blob/4ee0cb3ac1d6755b3fa0905974ddde181c95456c/Vagrantfile#L85

(see also https://superuser.com/questions/846964/how-to-add-a-host-only-adapter-to-a-virtualbox-machine-via-vagrant-file-config)

**Comment by giovannipizzi** [comment]
> what version of OSX are you running?

11.2 Big Sur

> I'm not sure how to automate disabling it

Note that in older VMs (like 20.06) it wasn't there (I'm quite sure I didn't change things, but it's true that I installed with an older version of the OS so maybe something magic happened? You can try anyway to re-install both and check the network settings; if you confirm that the 2nd network is there only for recent VMs, it means something has changed in the meantime in the way the OVA is created).

If this is the case, it means something has changed during provisioning.
In the worst case, when/just before/just after you create the OVA, you have to see if you can call the VirtualBox cmdline to disable that additional network.

**Comment by chrisjsewell** [comment]
>  it means something has changed in the meantime in the way the OVA is created

oh it definitely has: the line I link to above is part of the new build setup.

Obviously this is the first I've heard of anyone having any issues with it, but yeh hopefully then there is something that can be added to playbook-package.yml

**Comment by giovannipizzi** [comment]
Thanks! Quick question just to double check: did you create the VM for the tutorial of this week with or without this fix? (I still got the issue with that image)

**Comment by chrisjsewell** [comment]
Yet it was after this fix. It would be good to see if someone else can replicate this, because when @mbercx tested the VM (also on Mac) he didn't encounter this issue

**Comment by giovannipizzi** [comment]
Reopening, as at least another person during the tutorial (VBox 6.1.18 version, on Windows 10) had the same issue.

**Comment by giovannipizzi** [comment]
I checked, and the fix you mention should have fixed it however! Maybe it didn't run before you created the VM?
You can also check - if you import the OVA, do you get an enabled or disabled Adapter 2? (I get an enabled one, while it should be disabled)

**Comment by chrisjsewell** [comment]
> if you import the OVA, do you get an enabled or disabled Adapter 2?

From https://quantum-mobile.readthedocs.io/en/latest/releases/both/20.11.2a.html,
you can see there are the two network adapters selected

![image](https://user-images.githubusercontent.com/2997570/112023581-ae5f3480-8b33-11eb-936e-26c04c0238cc.png)

Whereas from https://quantum-mobile.readthedocs.io/en/latest/releases/both/21.03.18-qe.html,
only one

![image](https://user-images.githubusercontent.com/2997570/112022823-eca82400-8b32-11eb-8760-f2b01ffe20b1.png)

So its definitely disabled.
Perhaps it still doesn't like having the `vboxnet0` there even when disabled 🤷 

![image](https://user-images.githubusercontent.com/2997570/112023947-01d18280-8b34-11eb-9a65-3796e6445c0f.png)

Can you confirm that you only see the one network adapter when importing

**Comment by giovannipizzi** [comment]
Aaaahh now I see the issue: I think I downloaded an earlier version of the VM - probably the link in the docs was updated only later, I have installed the version called 21.03.17-lite. Is this the case?

I double checked with the 21.03.18-qe version, and indeed I get the same behaviour as your screenshots. I also started it and found no problem. So I'm going to close this issue!

**Comment by chrisjsewell** [comment]
> `21.03.17-lite`. Is this the case?

Ah yeh that was just one I made for Marnik to test against , before creating `21.03.18-qe` 👍
