### ISSUE TITLE
Default apps installed in AiiDAlab

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#168]
Is it possible to customise the default apps installed in AiiDAlab?
In particular, have the first app be the QE app?

**Comment by chrisjsewell** [comment]
I don't know about adjusting the order of the apps, but adding QE by default is already planned: https://github.com/marvel-nccr/ansible-role-aiidalab/blob/40fccf890bfd78241461ee7520e72541385ee36f/defaults/main.yml#L57-L58
(and I've already tested that it all works fine when installing it in v20.11.2a)

**Comment by chrisjsewell** [comment]
closed in https://github.com/marvel-nccr/ansible-role-aiidalab/pull/22
