### ISSUE TITLE
I want to install software that requires sudo password

### ISSUE THREAD

**Issue by mbmkeffat** [marvel-nccr/quantum-mobile#169]
May I have the sudo password for authentcation

**Comment by ltalirz** [comment]
Hi @mbmkeffat - the sudo password is `moritz` as documenter [here](https://quantum-mobile.readthedocs.io/en/latest/releases/both/20.11.2a.html) 

Just wondering - are you using the virtualbox edition or the docker container?

@chrisjsewell I think we should simply add an FAQ/troubleshooting item on this
