### ISSUE TITLE
Move cleanup tasks to playbook

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/quantum-mobile#172]
These are tasks that are not idempotent, and so can only be run after a machine has been fully provisioned.

As mentioned in https://github.com/marvel-nccr/quantum-mobile/issues/156#issuecomment-801875487,
existing cleanup tasks in simulation code roles were essentially deprecated, by ensuring the compilation was carried out in the `/tmp` folder (which is wiped when you restart the provisioned machine),
and the remaining cleanup tasks in `simulationbase` and `ubuntu_desktop` are duplicate, generic things (like cleaning the apt cache).

So I think these tasks can be removed from the roles, and just have a separate `playbook-cleanup.yml` that runs these tasks.

**Comment by chrisjsewell** [comment]
Note-to-self: another minor thing I propose to do there is clean the systemd log, e.g. `sudo journalctl --vacuum-size=2M` (https://ma.ttias.be/clear-systemd-journal/)

**Comment by ltalirz** [comment]
> the remaining cleanup tasks in `simulationbase` and `ubuntu_desktop` are duplicate, generic things (like cleaning the apt cache).

The original idea behind having the cleanup tasks inside the roles was that not all cleanup may be generic (and which cleanup to perform may depend on which roles are being run in the playbook).
Conceptually, I think it makes sense if each role knows how to clean up after itself.

However, it is true that moving the code builds to `/tmp` has removed the necessity for most code-dependent cleanup and if moving it to a playbook makes things easier to maintain that's also ok with me.
