### ISSUE TITLE
AiiDAlab-related things to be fixed before the next release.

### ISSUE THREAD

**Issue by yakutovicha** [marvel-nccr/quantum-mobile#174]
There a few AiiDAlab-related things that I consider important before making a new release of QuantumMobile:

- [ ] Rename the desktop icon: AiiDA Lab -> AiiDAlab
- [ ] Replace the rotating gears. [This is](https://github.com/aiidalab/aiidalab-docker-stack/blob/develop/Dockerfile#L78-L83) how we do it in the docker image
- [ ] Fix the appearance of the OPTIMADE client: the provider dropdown list isn't shown.

**Comment by yakutovicha** [comment]
Concerning the OPTIMADE client point. This is what I see in the QuantumMobile:

![image (3)](https://user-images.githubusercontent.com/13118485/112551960-3ce8e580-8dc2-11eb-986c-cc6fb0e34f43.png)

And this is how it should look like:

![Screenshot 2021-03-25 at 23 32 21](https://user-images.githubusercontent.com/13118485/112552040-686bd000-8dc2-11eb-8d25-e25460d66814.png)

**Comment by chrisjsewell** [comment]
Just to note here, after discussion with @yakutovicha, I have already found a potential way forward for the layout issue fix, in that I've noted in the debug console that ipywidgets does not seem to be able to find the requirejs package (a common Javascript package used for importing other packages).
I'll have a look and see why it isn't being installed into jupyter's Javascript environment

**Comment by chrisjsewell** [comment]
> Fix the appearance of the OPTIMADE client: the provider dropdown list isn't shown.

The issue here was that `ipywidgets-extended` was not installed.

I have not seen this listed in any of the app requirements, and the same with ipytree (cc also @csadorf)

**Comment by csadorf** [comment]
>  have not seen this listed in any of the app requirements, and the same with ipytree (is this actually used somewhere?)
> 
> I'm adding `ipywidgets-extended` to the aiidalab-qe jupyter requirements for now
> 
> (cc also @csadorf)

The `ipywidgets-extended` package is a [dependency of optimade-client](https://github.com/CasperWA/voila-optimade-client/blob/f6bada8e030b5e584f55623d8a51cd445ca7fec7/requirements.txt#L5), which is a [dependency of aiidalab-widgets-base](https://github.com/aiidalab/aiidalab-widgets-base/blob/dfa2d07dd796db98958f6054376e1ee22d41ecd4/metadata.json#L17) which is a [dependency of the QE app](https://github.com/aiidalab/aiidalab-qe/blob/5006b47be245d45dab75f2d4c4cdd29f159323a3/requirements.txt#L2). The `ipywidgets-extended` dependency is therefore only an indirect dependency of the QE app.

The `ipytree`package is a dependency of the [aiidalab-widgets-base develop branch](https://github.com/aiidalab/aiidalab-widgets-base/search?q=ipytree), but we apparently forgot to add it to the requirements. That would need to be fixed prior to the next release, so I'm proposing to add it in https://github.com/aiidalab/aiidalab-widgets-base/pull/195 .

**Comment by chrisjsewell** [comment]
thanks

> The ipywidgets-extended dependency is therefore only an indirect dependency of the QE app.

but if this is not installed into the jupyter environment, then the QE app is effectively broken, so surely it has to be added in the requirements of least one of the base or qe app, or QM will never know to install it

**Comment by chrisjsewell** [comment]
Note currently optimade-client is installed into the aiida environment, but not the jupyter one, which is why ipywidgets-extended is missing
