### ISSUE TITLE
Set the correct `mpirun_command` to go with the `localhost` computer for the AiiDA install

### ISSUE THREAD

**Issue by sphuber** [marvel-nccr/quantum-mobile#177]
The localhost computer is configured to use the SLURM scheduler but the `mpirun_command` uses `mpirun` instead of `srun`. Fixing this is blocked by the following PR for the AiiDA ansible role: https://github.com/marvel-nccr/ansible-role-aiida/pull/69

**Comment by ltalirz** [comment]
I'm not sure that is really necessary, see https://www.open-mpi.org/faq/?category=slurm

**Comment by sphuber** [comment]
This came during a discussion on an [issue for `aiida-common-workflows`](https://github.com/aiidateam/aiida-common-workflows/issues/180) where a CP2K run wasn't running properly in parallel. The [suspicion was raised](https://github.com/aiidateam/aiida-common-workflows/issues/180#issuecomment-818683842) that it might had to do with using `mpirun` instead of `srun`, but it seems indeed that this is not necessarily required. Fine to close this issue for now.
