### ISSUE TITLE
Virtual box error when tried to run Quantum mobile

### ISSUE THREAD

**Issue by Shruthicheth** [marvel-nccr/quantum-mobile#197]
I downloaded virtual box and imported quantum mobile. I have windows10 with 64bit processor. when I tried to use normal start in quantum mobile through virtual box it shows an error message
 
Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).</p>
<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED).</p>
<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

</body></html>

please help!! what should i do?

**Comment by ltalirz** [comment]
Hi @Shruthicheth , you might want to reboot into the BIOS of your laptop and enable VT-x?

**Comment by Shruthicheth** [comment]
Hi @ltalirz. yes,  the answer is very much in the question!!!! :) yes i enabled the VT-x. I am able to run Quantum Espresso Successfully. Thank you so much for the timely help,
