### ISSUE TITLE
preconfigure common supercomputers

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#2]
- [x] modularize computer setup
- [ ] add piz daint
- [ ] add marconi
- [ ] add bellatrix
- [ ] add Deneb
- [x] add fidis
- [ ] think about how to version these things

**Comment by giovannipizzi** [comment]
I think we should also add a few common codes on the supercomputers (e.g. QE)
Also, for EPFL, I would also add bellatrix and Deneb if we want to have the epfl supercomputers (I'm fixing the original comment now)

**Comment by ltalirz** [comment]
@giovannipizzi The reason, I didn't continue here was because I guess for systems like Daint with 
a separate login machine one needs to set up ssh tunnels, right? Should we do that?

**Comment by giovannipizzi** [comment]
No, one just needs to pass the right command to the ssh proxy, that's the same for everyone (going through Ela). Maybe however the simplest is to put in the machine the Jupyter notebooks for the MaterialsCloud, in particular the mc-cscs by Ole and the mc-epfl? They work also locally (but ideally probably we'll need to install also the app mode).

**Comment by ltalirz** [comment]
that sounds like a very good idea!

**Comment by ltalirz** [comment]
commit 310901e adds jupyter notebooks + app mode
As far as quantum-mobile is concerned, I believe this resolves the issue.

![screen shot 2018-01-10 at 18 00 10](https://user-images.githubusercontent.com/1053245/34785000-2cc77982-f630-11e7-9c52-3cacc6154f25.png)

One now just needs to add the remaining clusters to the mc-epfl app.
