### ISSUE TITLE
startup messages? shared folder?

### ISSUE THREAD

**Issue by stefaan-cottenier** [marvel-nccr/quantum-mobile#214]
I did a health check of quantum-mobile in preparation for the next edition of the course in which I use it (beta.compmatphys.org). Two issues noted, about which I'd like to hear the opinion of the developers:

1) There are several 'Failed' messages during the startup of the VM, including a 5m02s procedure to fix something (repeated at every statrtup). The VM appears to working normally afterwards, but this was definitely not there before. Any reason for this? Anythink I can do to avoid it?

2) Somehow creating a shared folder does not work (any more). The folder has the proper content at the moment the share is created (i.e. I can see in the VM the files that were in the local folder before I shared it). But new files that are created (at either side) are not shared. What may be wrong here?

All of this is for QM 21.05.1 in VirtualBox 7.0.

Thanks!
Stefaan

**Comment by ltalirz** [comment]
Hi @giovannipizzi @chrisjsewell , who is currently maintaining the Quantum Mobile and could have a look into this?

**Comment by unkcpz** [comment]
Hi @stefaan-cottenier, thanks for reporting the issues.
Did you try the new image [v23.04.3](https://quantum-mobile.readthedocs.io/en/latest/releases/versions/23.04.03.html), let us know if there are the same issues.

@ltalirz, after Chris leave the team last month, me and @mbercx will take over the responsibility to maintain this.

**Comment by stefaan-cottenier** [comment]
Indeed, v23.04.3 works fine. The reason I did not notice before that a new version was available is that https://github.com/marvel-nccr/quantum-mobile/releases/ still gives v21 as the latest one. That page doesn't seem to be kept up to date. Can you confirm that https://quantum-mobile.readthedocs.io/en/latest/releases/index.html is the place to get the latest version? (I'll update the links in the course accordingly)

Thanks!

**Comment by unkcpz** [comment]
I see, thanks! Sure, I'll take care of the releases page.
