### ISSUE TITLE
cif2cell missing in QM?

### ISSUE THREAD

**Issue by stefaan-cottenier** [marvel-nccr/quantum-mobile#216]
While testing Quantum Mobile 23.04.03 in order to use it with a course that starts on Sep 25, I notice that cif2cell is not available any longer. It used to be there in some earlier versions. It is quite convenient to transform cif files into Quantum Espresso input files.

1) Is it possible to get cif2cell back into Quantum Mobile

2) If not possible, or if not possible soon, which procedure do you recommend to get it installed as a user? (this was the default a few years ago, but I remember it was quite easy to mess up the system that way)

Thanks!
Stefaan

**Comment by stefaan-cottenier** [comment]
Well, 

pip install cif2cell

seems to work after all. Hence, no big deal. Sorry for bothering...!

**Comment by ltalirz** [comment]
One thing I would mention is that cif2cell is currently not actively maintained https://github.com/torbjornbjorkman/cif2cell/issues/35 (a new maintainer who uses it could solve that problem rather easily).

I have never really used cif2cell myself, but I suspect a large fraction of what cif2cell may already be covered by [`ase convert`](https://wiki.fysik.dtu.dk/ase/cmdline.html) and the [formats it supports](https://wiki.fysik.dtu.dk/ase/ase/io/io.html#module-ase.io) (or could be integrated into that cli)

I'd be interested in a comment by @stefaan-cottenier  on that topic.
