### ISSUE TITLE
user wallpaper not set directly

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#35]
On my machine, `vagrant up` works flawlessly, except that the user wallpaper is not set to the MARVEL one.
When one runs the `customizations` role 2 more times, it seems to works. No idea why.

**Comment by giovannipizzi** [comment]
In which order are the tasks run? When I was writing it, it needs to have the X server (started when starting lightdm) already started, and (I think) the user not logged in (or some variants of these... you can check the order in the version of a few weeks ago).

**Comment by ltalirz** [comment]
now seems to work in ubuntu-18.04 branch
