### ISSUE TITLE
Quantum ESPRESSO (at least) prints IEEE_DENORMAL and similar floating-point exceptions

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#52]
FPE are harmless, but ugly to see, they look like
`Note: The following floating-point exceptions are signalling: IEEE_DENORMAL`.
Apparently, this happens only if the fortran code uses `STOP` explicitly.

To remove the, recompiling (in gfortran) with `-ffpe-summary=none` should hide them.
I will try to see if this solves the issue.

@ltalirz (I mention you just FYI, in case the same problem appears again for other codes).

**Comment by ltalirz** [comment]
Hi @krishna1730 , the flag needs to be provided at compile time, not at run time.

In any case, it won't make a difference for the result, it simply silences the warning.

As Giovanni mentioned, floating point exceptions are usually ([but not always](https://wiki.usask.ca/display/MESH/IEEE+errors+using+GNU+compiler)) harmless. E.g. IEEE_DENORMAL means that a number is getting too small to be represented accurately, i.e. one or more leading digits in the mantissa become zero.

In 64bit floating point those are pretty small numbers (<1e-300).

**Comment by ltalirz** [comment]
Note: The floating point exception is not why your run terminated, that will be for a different reason

**Comment by krishna1730** [comment]
hi @ltalirz thank you for response, is there any solution for it, my system has 4 cores and 64 bit and i am new to UBUNTU OS.

**Comment by ltalirz** [comment]
Maybe try running without redirecting output? It may have some pointers.

In general, for Quantum ESPRESSO support we recommend asking on the QE mailing list; we cannot provide dedicated support for the codes themselves in the Quantum Mobile side

**Comment by digdig** [comment]
Can you detailed where to add this option? It may help for the newcomers.

**Comment by ltalirz** [comment]
Hi @digdig , as you can see in the fix https://github.com/marvel-nccr/quantum-mobile/commit/d8fd3a6548d273b418a8cab80cbf7466d5c0e034 you need to set it at the configure stage, for example

```
FFLAGS='-O3 -g -ffpe-summary=none' ./configure --enable-parallel
```

Note, however, that this flag only changes the _reporting_ in the QE log file, it does not change the numerical behavior of the code.
