### ISSUE TITLE
nglview, seek path and more generally WebGL in Firefox inside the VM

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#56]
nglview, seek path and more generally WebGL do not work inside the VM with Firefox.
Currently checked with Firefox 58.x provided by ubuntu, and also downloading Firefox 59.x.

The error I get, after investigation, is directly due to Firefox blacklisting the graphics drivers and disabling WebGL. From `about:support`:
```
WebGL creation failed:
* Refused to create native OpenGL context because of blacklist entry:
* Exhausted GL driver options.
```
and a similar error for WebGL2.

Also, forcefully enabling `webgl.force-enabled=True` from `about:config` makes the tab crash when opening a WebGL page.

Note that I have 3D acceleration enabled in the settings of the VM.

Installing manually Chrome instead works (apparently Chrome has a smaller blacklist).

I can try to investigate more if there is a version of the Guest Additions that is not blacklisted, but I doubt so (and I couldn't find much info on the web).

I think a simple solution could be to install Chrome as the default browser. @ltalirz what do you think? (I installed Chrome by downloading the .deb from the website, maybe there's a better way to automate this in ansible?)

**Comment by ltalirz** [comment]
Switch to Chromium is fine for me, if we need the webgl support.
Perhaps monitor the size of the install.

**Comment by giovannipizzi** [comment]
Fixed in fc7d344a2428ba97 (plus some later commits to improve usability). Firefox is not removed, just chromium-browser added and set as the default browser.

**Comment by ltalirz** [comment]
Just for reference: the new image is ~350MB larger than the previous one without Chrome.
Not ideal... if we manage to get things running in firefox at some point, we may want to go back.

**Comment by giovannipizzi** [comment]
from what I read, I don't think it will be possible... the drivers are blacklisted by Firefox. maybe instead we can uninstall Firefox? we just need to decide how to avoid that Ubuntu-desktop reinstalls it at every run of ansible

**Comment by ltalirz** [comment]
This is just to point out that the size comparison based on the image size is not necessarily accurate (I thought nothing else had changed, but in retrospect this isn't true). If one is interested to know this number, one should look at the size of the packages installed by chromium.
