### ISSUE TITLE
avoid too many jupyter kernels

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#57]
If possible it would be nice that the second time one clicks on the desktop on the "Jupyter Apps" icon, one just has a browser opened connected to an existing kernel, rather than starting each time a new server on a different port.

There is probably a good automatic way to do this, but as a reference, `jupyter notebook list` lists all servers (and has a `--json` option).

**Comment by ltalirz** [comment]
what is the advantage here?

**Comment by giovannipizzi** [comment]
That if one closes the browser, than one can easily reconnect to the same server, rather than opening a new one that will keep running on a new port until the reboot

**Comment by ltalirz** [comment]
Ok, so perhaps what I should look into then is to make sure the server is shut down, when one closes the browser...

**Comment by giovannipizzi** [comment]
I'm not sure this is possible. Anyway, not urgent, I'll also look into this.

**Comment by ltalirz** [comment]
fixed in 389171bee70d53b855d1c2b96cd4b17e71694128
