### ISSUE TITLE
Wrong (no?) cp2k data directory

### ISSUE THREAD

**Issue by edditler** [marvel-nccr/quantum-mobile#59]
The data directory CP2K tries to read from a folder that does not exist. It is pointed to `/gpfs/data/krack/rt/released/cp2k/data` and fails to find the potentials and so on. Some part of the data directory is stored in `/home/max/codes/cp2k-5.1/` and can be made available as

```bash
sudo mkdir -p /gpfs/data/krack/rt/released/cp2k
cd /gpfs/data/krack/rt/released/cp2k
ln --symbolic /home/max/codes/cp2k-5.1/ data/
```
But there is a lot missing.

Did I overlook something or would one need to supply the data directory to each calculation?

**Comment by ltalirz** [comment]
Hi Ed, thanks for the notice. I'll look into it - in the meanwhile I think you can set the DATA directory via the environment variable $CP2K_DATA_DIR (which we should preconfigure).

**Comment by ltalirz** [comment]
And yes, we haven't downloaded all possible data files - just the ones that Ole downloaded for the mc docker stack.
Perhaps we should include more...

**Comment by edditler** [comment]
This way the materialscloud apps developed in the nanotech@surfaces group fail to submit calculations. On the other hand most of them can't be run in a reasonable way on a local machine, so it's also not super urgent.

The whole data directory is available at https://github.com/cp2k/cp2k/tree/master/cp2k/data

**Comment by ltalirz** [comment]
well, we'll need to take the one from the 5.1 release to be on the safe side.
for this we currently have to download the full source, which is not ideal but also not a problem.

I've posted to the cp2k mailing list for them to consider adding a separate archive
https://groups.google.com/forum/#!topic/cp2k/feKkD6KH0i0
