### ISSUE TITLE
add aiida demos

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#6]

**Comment by ltalirz** [comment]
@giovannipizzi If you let me know what exactly to add, this might be a good addition - then, the examples folder won't just contain a "work in progress"

**Comment by giovannipizzi** [comment]
https://github.com/aiidateam/aiida_demos
(at this point anyway I would wait before the next release, so we can also use the occasion to update the demos).

**Comment by ltalirz** [comment]
Fixed in 6aa5a870bd2d6d5e8056c751f0291e5dd7324b88.
@giovannipizzi I'll probably release a 17.12.0 soon. For the moment it's ok if the aiida demos aren't updated yet. The updated version will be pulled automatically, when they are.
