### ISSUE TITLE
host quantum mobile on the Materials Cloud Archive

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#64]
suggestion by @giovannipizzi 

This would have the benefit of providing a citable DOI to anyone who uses it.

The only problem I currently see is the doi identifiers we are using, which are bound to confuse people.
How should one know that 2017.0009/v7 means Quantum mobile 18.04 (just a fake example to illustrate the point)?

**Comment by ltalirz** [comment]
Mentioning @giovannipizzi for comment.

**Comment by giovannipizzi** [comment]
I don't know, I see the advantages of having it on the archive (but then we should "lift" the requirement of entries being linked to peer-reviewed research papers (at least potentially - it's true we might link it to the Materials Cloud + Quantum Mobile paper).
For the identifiers, I see your point - that's a discussion we need to have next week with Nicola, I think. We might think to move to random IDs (keeping the materialscloud: prefix in the DOI, I think, and versioning). Would this be better? Should we have/allow short or easy-to-remember names as well or this is not a problem? (Note that changing the ID syntax requires some change to the current archive code).

**Comment by ltalirz** [comment]
> I don't know, I see the advantages of having it on the archive (but then we should "lift" the requirement of entries being linked to peer-reviewed research papers (at least potentially - it's true we might link it to the Materials Cloud + Quantum Mobile paper).

Ok, so for the moment I'll close this.

> For the identifiers, I see your point - that's a discussion we need to have next week with Nicola, I think. We might think to move to random IDs (keeping the materialscloud: prefix in the DOI, I think, and versioning). Would this be better?

I'm definitely in favor of this.

> Should we have/allow short or easy-to-remember names as well or this is not a problem?

I believe people have thought about this for some time and come to the conclusion that it is not a good idea to keep semantic information in the ID.

>  (Note that changing the ID syntax requires some change to the current archive code).

Sure, we'll need to deal with that.
