### ISSUE TITLE
ansible provisioning using users without sudo privileges

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#67]
## Goal
We would like to provision a VM using a user `regularuser` that may not have sudo privileges.
Whenever superuser privileges are required, ansible should become a superuser (e.g. `admin`).

## Problems
The first decision is to choose the ssh user, which ansible uses to log in.

 1. The straightforward solution would seem to be to log in using `admin`, then immediately `become` `regularuser`. When superuser privileges are required, one would `become` `admin` again. This obviously needs two different meanings of `become` in the same playbook, ~and unfortunately, ansible currently has no mechanism for doing  this~ and this can be achived using `become_user`.

 2. One can log in using `regularuser` and escalate privileges, when needed. This can be done either via `sudo <cmd>` or via `su admin; cmd...`, but this means the admin user needs to have a password and one needs to provide the corresponding passwords to ansible.

## Solution

I believe only the second option is currently viable. This means  either `regularuser` needs a password & sudo privileges or `admin` needs to have a password.

I guess, setting the password for `admin` and disabling SSH access via password is the way to go.

@giovannipizzi Do you agree?

**Comment by ltalirz** [comment]
Yep, that works.

**Comment by ltalirz** [comment]
So, I've now done first tests on going via route 1, see https://github.com/marvel-nccr/ansible-role-quantum-espresso

 * I've introduced a variable `root_user`. We would add this variable to all roles that need root privileges. This breaks the naming convention for variables, but just a little bit and would allow for a straightforward way of globally setting the root user
 * I've replaced `{{ ansible_env.HOME }}` by `${HOME}`, which ansible simply uses/writes verbatim (expansion is done by the shell). I guess in most cases that should work, but it means that any environment variables set e.g. in `.profile` will have `${HOME}` and not `/home/aiida` in them, i.e. if sourced by a different user they would correspond to different paths.

I currently don't see any serious problems with this strategy,
except for the fact that I can't shake the feeling we are trying to get ansible to do something it isn't really designed to do at the moment.
@giovannipizzi Any final comments before I migrate the other roles?

**Comment by ltalirz** [comment]
problem: when adding AiiDA as a system service, something like `PIDFile={{ ansible_env.HOME }}/.aiida/daemon/log/celery.pid` won't do

**Comment by giovannipizzi** [comment]
Why? Is this set in a file?
I think the strategy here then should be run as the first task a task that reads the environment variable and sets it as facts (there should be an ansible module already for that).
Then, use it as from the ansible variable when writing it in a file.

Some links that might (or might not) be useful:
- https://docs.ansible.com/ansible/2.5/plugins/lookup/env.html 
- https://galaxy.ansible.com/franklinkim/environment/

**Comment by ltalirz** [comment]
This issue of determining the home directory of the current use is an [open (but closed) ansible issue](https://github.com/ansible/ansible/issues/15901) (see also [stackoverflow](https://stackoverflow.com/questions/33343215/how-to-get-remote-users-home-directory-in-ansible) )

The current workaround seems to be
```
- name: account $HOME
  shell: "echo $HOME"
  register: account_homedir
  changed_when: false
  check_mode: no
```

**Comment by ltalirz** [comment]
Since this really seems to be the current state of the art (Note: the [env lookup](https://docs.ansible.com/ansible/2.5/plugins/lookup/env.html) only returns the values from the controller machine), I propose we simply use `${HOME}` by default
and use the workaround from above whenever it's needed (e.g. for the daemon service).

**Comment by ltalirz** [comment]
There is another problem - when going via route 1, we cannot reuse ansible roles of anyone else:
First, we need to set `become_user` for every instance where they use `become` 
and second, their roles may not be taking into account the differences between the current user & the default user.

I didn't think of this before, but this seems to me like a big drawback of route 1.
I think for the next quantum mobile release, I am going to have to go back to route 2.
Note: The roles that have been prepared for route 1 should still work with route 2, but some of the functionality will be "dormant".

**Comment by giovannipizzi** [comment]
Can't we set `become_user` globally?
Or the option used in the `aws` branch, where roles are divided between those where one needs to have sudo access, and those where one needs to be a regular user?

**Comment by ltalirz** [comment]
> Can't we set  `become_user` globally?

Unfortunately not because in route 1 there are two `become_users`: the regular user and the superuser.

> Or the option used in the aws branch, where roles are divided between those where one needs to have sudo access, and those where one needs to be a regular user?

Well, as long as we have full control over a role, we can make it work (as I currently do in the marvel-nccr roles).
Of course, this is no longer possible, when we want to reuse roles written by other people (which was the point I was trying to make).

Because it was not a big effort, I edited the one external role we currently use in Quantum Mobile (gantsign.default-browser), but I predict that this problem will bite us again in the future.

**Comment by giovannipizzi** [comment]
Ok. So if I understand correctly, in `gantsign.default-browser`, there are parts done with `become: True` and others not, so it basically expects that the user has sudo access?

**Comment by ltalirz** [comment]
> Ok. So if I understand correctly, in gantsign.default-browser, there are parts done with become: True and others not, so it basically expects that the user has sudo access?

Correct. Most ansible roles assume this.

**Comment by ltalirz** [comment]
For most roles, this problem could be avoided by setting them up system-wide, in which case there is no need for a first `become_user`.

For Quantum Mobile, i.e. an environment that we fully control, I actually see no reason not to set up the codes & the python packages system wide. This applies in particular to workhorses, where we might want to add multiple user accounts for running calculations.

At first glance, the only roles where things really need to be set up for a particular user, are the profile setup of aiida and the apps of aiidalab.
@giovannipizzi Do you agree?

**Comment by ltalirz** [comment]
@giovannipizzi Just pinging back concerning the question above.

Clement Onime from ICTP who installed Quantum Mobile on 50 machines in Addis, actually also made all codes available to all users of the machine.

**Comment by ltalirz** [comment]
Moving forward with my suggestion [above](https://github.com/marvel-nccr/quantum-mobile/issues/67#issuecomment-396006748). Closing.
