### ISSUE TITLE
virtualbox *very* slow on Macbook Pro 2018 without 3d acceleration

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#89]
@danieleongari encountered a strange case where Quantum Mobile 18.06 with 3d acceleration disabled is *very* slow on a MacBook Pro Retina 2018 13" with Intel Iris Plus Graphics 655 running macOS Mojave 10.14.2 (meaning: dragging a window from one place to another takes on the order of 1 **minute** to respond).

Interestingly, the problem can *not* be reproduced on a MacBook Pro Retina 2015 with Intel Iris Pro running the same operating system.

Note: 
 * The problem only concerns the case when 3d acceleration is disabled. When 3d acceleration is enabled, QM 18.06 runs smoothly on both macbooks
 * we checked that it is not due to lack of resources allocated to the VM
 * we checked that the memory pressure remains fine when running virtualbox
 * booting showed "intel_rapl: no valid rapl domains" message, however enabling/disabling PAE as explained [here](https://askubuntu.com/a/449577/715125) did not impact performance

**Comment by giovannipizzi** [comment]
See #8 - 3D acceleration should be on

**Comment by chrisjsewell** [comment]
Given that 3D acceleration is enabled by default, can we close this?
https://github.com/marvel-nccr/quantum-mobile/blob/b2632be01b2f21f4416833f79702758d20026739/Vagrantfile#L39
