### ISSUE TITLE
name changed on ansible galaxy

### ISSUE THREAD

**Issue by adegomme** [marvel-nccr/quantum-mobile#90]
After encountering 
 [WARNING]: - marvel-nccr.ubuntu-desktop was NOT installed successfully: - sorry, marvel-nccr.ubuntu-desktop was not found on https://galaxy.ansible.com.
when trying the "ansible-galaxy install -r requirements.yml" line, it appears both ubuntu-desktop and quantum-mobile-customizations are now using underscores in their names. 
requirements.yml file should probably be updated to match these new names.

**Comment by ltalirz** [comment]
Should be fixed in 9e6a0b3a743bd6f1c7218361466aa8df04c86910 for `ubuntu-18.04` branch.
planning to merge branch into master soon.

**Comment by adegomme** [comment]
Hi,
I just tried, and saw that quantum_espresso was still named quantum-espresso, on ansible galaxy.

**Comment by ltalirz** [comment]
Sorry about this and thanks for checking!
Just pushed a fix https://github.com/marvel-nccr/ansible-role-quantum-espresso/commit/8358bac987186cce5c84bd67325a0987d983285a

Should hopefully resolve this in ~10 minutes.

**Comment by ltalirz** [comment]
also added a small fix to the playbook c608c0ec696e133dde78a408ef0a1ee3e973ea2a

**Comment by adegomme** [comment]
I had to change back the playbook.yml to ansible_prerequisites to proceed, but quantum_espresso at line 88 had to be changed to quantum-espresso.

Going further, in Vagrantfile, the line 35 did not work on my Ubuntu 18.04, as it seems that coreaudio is only a MacOS feature. I commented it out, but maybe using pulse instead can work for linux hosts.

**Comment by ltalirz** [comment]
Hi @adegomme 

> In the playbook, quantum_espresso at line 88 has to be changed back to quantum-espresso as well.

hm... why?
The role on ansible galaxy [has been renamed to quantum_espresso](https://galaxy.ansible.com/marvel-nccr/quantum_espresso)

> Going further, in Vagrantfile, the line 35 did not work on my Ubuntu 18.04, as it seems that coreaudio is only a MacOS feature. I commented it out, but maybe using pulse instead can work for linux hosts

Thanks for pointing this out!
I've disabled this now until I find time to look for a proper fix #91

**Comment by adegomme** [comment]
My bad, I tried the build on friday, just before the change, and did not try again this morning before posting. This can be closed, then.
