### ISSUE TITLE
building on windows

### ISSUE THREAD

**Issue by zhubonan** [marvel-nccr/quantum-mobile#94]
As stated in the documents, it is possible to build on windows but a few modifications are needed. I tried to build and found it is indeed the case. Any hint what the modifications be?

1. `ansible` is not available on windows. One solution could be to use `ansible_local` provisioner, but I have not succeed with it. 
2. Alternatively, `ansible` may be installed in WSL.
3. Any others?

**Comment by ltalirz** [comment]
> it is possible to build on windows but a few modifications are needed

Well, to be exact I say it *might* work under windows ;-)

> ansible is not available on windows. One solution could be to use ansible_local provisioner, but I have not succeed with it.

Hm, I wasn't aware of that ;-)

> Alternatively, ansible may be installed in WSL.

Yeah, this seems the only option in this case.
Happy hear about your progress!

**Comment by zhubonan** [comment]
I got it to work with vagrant and ansible installed and run in WSL, VirtualBox is installed in windows.
No modification is needed to the repository itself.

The following lines should be added to the .bashrc in WSL:
```
# Enable WSL feature in vagrant
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"  
# Added virtualbox under windows to $PATH
export PATH="${PATH}:/mnt/c/Program Files/Oracle/VirtualBox" PATH
```
For the rest, I just followed the instruction in the REDAME.md file as if I was in Ubuntu.

**Comment by ltalirz** [comment]
Fantastic, thanks @zhubonan !

Does this look right? https://github.com/marvel-nccr/quantum-mobile/wiki/Instructions-for-building-Quantum-Mobile

> export PATH="${PATH}:/mnt/c/Program Files/Oracle/VirtualBox" PATH

Essentially, is the extra PATH at the end a typo?

**Comment by zhubonan** [comment]
Looks good to me, maybe add 'follow the instructions in README.md' in WSL.
The extra PATH is just a typo.

**Comment by ltalirz** [comment]
Done

**Comment by ltalirz** [comment]
By the way, if you intend to add roles for Quantum Mobile, I'm happy to host them under the marvel-nccr organization (both in github and under ansible-galaxy) so that people can easily find them
