### ISSUE TITLE
Quantum Mobile UI gets super slow after a few minutes of usage

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/quantum-mobile#99]
This happens in VirtualBox 6.
Apparently a solution is to tell users to go in the settings, under the "Graphics" card, and change the Graphics Controller value to "VMSVGA"

(Credits to original solution that was posted [here](https://jsephler.co.uk/slow-laggy-poor-graphics-performance-linux-guest-virtualbox-6-0/))

I didn't need to reinstall the Guest Additions, and the experience seems now reasonable. We might want to 
- tell this to users
- check if it's easy to set this flag in the OVA (probably in the provision step we can call the cmdline commands of VirtualBox to set this value on the image, and this gets exported?)

**Comment by ltalirz** [comment]
great - I've just added this to https://github.com/marvel-nccr/quantum-mobile/wiki/Frequently-Asked-Questions

indeed we might be able to select this in the vagrant setup

**Comment by ltalirz** [comment]
added fix to vagrant file in c615b851b45e583c45791c2d919c2aa5f7090b2b

**Comment by ltalirz** [comment]
closing for now, can reopen if issue persists.
